'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ChevronLeft, ChevronRight, Plus, Trash2, Sparkles, Globe2 } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { getSuggestedRequirements } from '@/lib/request-requirements'

const types = {
  توظيف: ['مهندس مشاريع','مهندس مكتب فني','مهندس مشروع','مهندس مشتريات','محاسب موقع','مسؤول حركة','مدخل بيانات','موارد بشرية','أخرى'],
  تدريب: ['تدريب تعاوني','تدريب صيفي','تدريب مهني','أخرى'],
  تجربة: ['تجربة وظيفية','فترة تجربة','تجربة ميدانية','أخرى'],
  تقييم: ['تقييم موظف','تقييم مرشح','تقييم أداء','أخرى'],
} as const

type Req = { text: string; weight: number; category: string; required: boolean }
const round2 = (value:number) => Number(value.toFixed(2))

export default function NewRequest(){
 const router=useRouter(); const [step,setStep]=useState(1); const [kind,setKind]=useState(''); const [detail,setDetail]=useState(''); const [reqs,setReqs]=useState<Req[]>([{text:'',weight:100,category:'عام',required:false}]); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [researching,setResearching]=useState(false); const [researchDone,setResearchDone]=useState(false)
 const total=useMemo(()=>round2(reqs.reduce((s,x)=>s+(Number(x.weight)||0),0)),[reqs]); const hasValidWeight=Math.abs(total-100)<.01; const cleanRequirements=useMemo(()=>reqs.filter(x=>x.text.trim()),[reqs])
 const add=()=>setReqs(prev=>[...prev,{text:'',weight:0,category:'عام',required:false}])
 const researchRequirements=async()=>{if(!detail.trim())return;setResearching(true);setResearchDone(false);setError('');try{const response=await fetch(`/api/job-requirements?job=${encodeURIComponent(detail.trim())}&type=${encodeURIComponent(kind)}`,{cache:'no-store'});const data=await response.json();const local=getSuggestedRequirements(detail.trim());const source=[...(data.requirements||[]),...local];const existing=new Set(reqs.map(x=>x.text.trim().toLowerCase()).filter(Boolean));const fresh=source.filter((x:any)=>x?.name&&!existing.has(String(x.name).trim().toLowerCase())).map((x:any)=>({text:String(x.name).trim(),category:String(x.category||'عام'),weight:0,required:Boolean(x.required)}));if(!fresh.length){setResearchDone(true);setError('تمت مراجعة المتطلبات ولا توجد متطلبات إضافية؛ يمكنك إضافة متطلبات يدويًا.');return}const all=[...reqs.filter(x=>x.text.trim()),...fresh];const equal=round2(100/all.length);setReqs(all.map((x,i)=>({...x,weight:i===all.length-1?round2(100-equal*(all.length-1)):equal})));setResearchDone(true)}catch{setError('تعذر الوصول للبحث الخارجي الآن، وتم الاحتفاظ بالمكتبة الداخلية. يمكنك الاستمرار وإضافة متطلبات يدويًا.');const local=getSuggestedRequirements(detail.trim());const existing=new Set(reqs.map(x=>x.text.trim().toLowerCase()).filter(Boolean));const fresh=local.filter(x=>!existing.has(x.name.toLowerCase())).map(x=>({text:x.name,category:x.category,weight:0,required:Boolean(x.required)}));const all=[...reqs.filter(x=>x.text.trim()),...fresh];if(fresh.length){const equal=round2(100/all.length);setReqs(all.map((x,i)=>({...x,weight:i===all.length-1?round2(100-equal*(all.length-1)):equal})))} }finally{setResearching(false)}}
 useEffect(()=>{if(step===3&&detail&&!researchDone)researchRequirements()},[step,detail,researchDone])
 const update=(i:number,patch:Partial<Req>)=>{setReqs(prev=>prev.map((x,j)=>j===i?{...x,...patch}:x));setError('')}; const remove=(i:number)=>{setReqs(prev=>prev.filter((_,j)=>j!==i));setError('')}
 const goNext=()=>{if(step===1&&!kind){setError('اختر نوع الطلب.');return}if(step===2&&!detail.trim()){setError('اكتب أو اختر النوع الدقيق للطلب.');return}if(step===3){if(!cleanRequirements.length){setError('أضف متطلبًا واحدًا على الأقل قبل الانتقال للمرحلة التالية.');return}if(!hasValidWeight){setError(`يجب أن يكون مجموع أوزان المتطلبات 100%. المجموع الحالي ${total.toFixed(2)}%.`);return}}setError('');setStep(x=>x+1)}
 const submit=async()=>{setError('');if(!supabase){setError('لم يتم إعداد اتصال Supabase.');return}const clean=reqs.filter(x=>x.text.trim());const cleanTotal=round2(clean.reduce((s,x)=>s+(Number(x.weight)||0),0));if(!clean.length||Math.abs(cleanTotal-100)>=.01){setError('يجب أن يكون مجموع أوزان المتطلبات المدخلة 100%.');return}setSaving(true);const exactType=detail.trim();const {data:request,error:re}=await supabase.from('requests').insert({company_name:'البنية الاساسية للمقاولات',request_type:kind,exact_type:exactType,notes,status:'مفتوح'}).select().single();if(re||!request){setError(re?.message||'تعذر إنشاء الطلب.');setSaving(false);return}const {error:qe}=await supabase.from('request_requirements').insert(clean.map((x,i)=>({request_id:request.id,name:x.text.trim(),category:x.category||'عام',weight:round2(Number(x.weight)||0),required:x.required,sort_order:i})));if(qe){setError(qe.message||'تم إنشاء الطلب لكن تعذر حفظ المتطلبات.');setSaving(false);return}router.push(`/requests/${request.id}`)}
 return <main className="min-h-screen bg-[#f5f7fa]" dir="rtl"><header className="bg-[#09233f] text-white px-6 py-5"><div className="max-w-4xl mx-auto"><div className="text-[#d4a72c] font-bold">البنية الاساسية للمقاولات</div><h1 className="text-xl font-bold mt-1">إنشاء طلب جديد</h1></div></header><div className="max-w-4xl mx-auto p-5 md:p-10"><div className="flex items-center justify-between mb-8">{['نوع الطلب','النوع الدقيق','المتطلبات','المراجعة'].map((x,i)=><div key={x} className={`flex items-center gap-2 ${step===i+1?'text-[#b88618]':'text-slate-400'}`}><span className={`w-9 h-9 rounded-full flex items-center justify-center font-bold ${step>=i+1?'bg-[#09233f] text-white':'bg-slate-200'}`}>{i+1}</span><span className="hidden sm:block font-bold">{x}</span></div>)}</div><div className="card p-6 md:p-8">
 {step===1&&<><h2 className="text-2xl font-bold text-[#09233f]">ما نوع الطلب؟</h2><p className="text-slate-500 mt-2 mb-6">اختر نوع الطلب الذي تريد إنشاؤه.</p><div className="grid sm:grid-cols-2 gap-4">{Object.keys(types).map(t=><button key={t} onClick={()=>{setKind(t);setDetail('');setResearchDone(false);setReqs([{text:'',weight:100,category:'عام',required:false}])}} className={`text-right p-5 rounded-xl border-2 ${kind===t?'border-[#b88618] bg-amber-50':'border-slate-200 hover:border-slate-300'}`}><b>{t}</b><div className="text-sm text-slate-500 mt-1">طلب {t}</div></button>)}</div></>}
 {step===2&&<><h2 className="text-2xl font-bold text-[#09233f]">حدد النوع الدقيق للطلب</h2><p className="text-slate-500 mt-2">يمكنك اختيار مسمى جاهز ثم تعديله، أو كتابة مسمى جديد بالكامل. عند الانتقال للمتطلبات سيتم البحث تلقائيًا عن متطلبات هذا المسمى.</p><input list="request-detail-options" value={detail} onChange={e=>{setDetail(e.target.value);setResearchDone(false)}} placeholder="اكتب المسمى الوظيفي / النوع الدقيق" className="input mt-5"/><datalist id="request-detail-options">{types[kind as keyof typeof types]?.map(t=><option key={t} value={t}/>)}</datalist><div className="grid sm:grid-cols-2 gap-3 mt-4">{types[kind as keyof typeof types]?.map(t=><button key={t} onClick={()=>{setDetail(t);setResearchDone(false)}} className={`p-4 rounded-xl border text-right ${detail===t?'border-[#b88618] bg-amber-50':''}`}>{t}</button>)}</div></>}
 {step===3&&<><h2 className="text-2xl font-bold text-[#09233f]">متطلبات الوظيفة</h2><p className="text-slate-500 mt-2">يتم أولًا تحميل متطلبات المسمى من المكتبة المتخصصة، ثم البحث المجاني على الإنترنت عن متطلبات السوق السعودية لهذا المسمى. جميع النتائج قابلة للتعديل والحذف والإضافة.</p><div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" onClick={researchRequirements} disabled={researching} className="inline-flex items-center gap-2 rounded-xl border border-[#b88618] bg-amber-50 px-4 py-3 font-bold text-[#8a6410] disabled:opacity-50">{researching?<><Sparkles size={18} className="animate-pulse"/> جاري البحث...</>:<><Globe2 size={18}/> بحث وتحديث المتطلبات من الإنترنت</>}</button>{researchDone&&!researching&&<span className="text-sm text-green-700 font-bold">تمت مراجعة المتطلبات تلقائيًا</span>}</div><div className="mt-6 overflow-x-auto"><div className="min-w-[720px] space-y-3"><div className="grid grid-cols-[1fr_130px_130px_90px_40px] gap-2 px-1 text-xs font-bold text-slate-500"><span>المتطلب</span><span>الوزن %</span><span>التصنيف</span><span>أساسي؟</span><span></span></div>{reqs.map((q,i)=><div className="grid grid-cols-[1fr_130px_130px_90px_40px] gap-2 items-center" key={i}><input value={q.text} onChange={e=>update(i,{text:e.target.value})} placeholder={`المتطلب ${i+1}`} className="input"/><input type="number" min="0" max="100" step="0.01" value={q.weight} onChange={e=>update(i,{weight:Number(e.target.value)})} className="input"/><select value={q.category} onChange={e=>update(i,{category:e.target.value})} className="input"><option>عام</option><option>مؤهل</option><option>مهارة فنية</option><option>برنامج هندسي</option><option>اعتماد</option><option>خبرة</option><option>إدارة</option><option>مشتريات</option><option>محاسبة</option><option>موارد بشرية</option><option>أداء</option><option>سلوك</option><option>سلامة</option><option>تشغيل</option></select><label className="flex items-center justify-center gap-2 text-sm whitespace-nowrap"><input type="checkbox" checked={q.required} onChange={e=>update(i,{required:e.target.checked})}/> أساسي</label>{reqs.length>1?<button type="button" onClick={()=>remove(i)} className="text-red-500 justify-self-center"><Trash2 size={19}/></button>:<span/>}</div>)}</div></div>{!cleanRequirements.length&&<div className="mt-5 rounded-xl bg-amber-50 p-4 text-amber-800">لا توجد متطلبات حتى الآن.</div>}<div className={`mt-5 rounded-xl p-4 font-bold ${hasValidWeight?'bg-green-50 text-green-700':'bg-amber-50 text-amber-700'}`}>إجمالي الأوزان: {total.toFixed(2)}%{!hasValidWeight&&<span className="mr-2 font-normal">— يجب أن يصبح 100%</span>}</div><button type="button" onClick={add} className="mt-4 flex items-center gap-2 text-[#b88618] font-bold"><Plus size={18}/> إضافة متطلب يدوي</button></>}
 {step===4&&<><h2 className="text-2xl font-bold text-[#09233f]">مراجعة الطلب</h2><div className="grid sm:grid-cols-2 gap-4 mt-6"><div><span className="text-sm text-slate-500">نوع الطلب</span><p className="font-bold">{kind}</p></div><div><span className="text-sm text-slate-500">النوع الدقيق</span><p className="font-bold">{detail}</p></div></div><div className="mt-6"><span className="text-sm text-slate-500">المتطلبات ({cleanRequirements.length})</span>{cleanRequirements.map((x,i)=><div key={i} className="flex justify-between gap-4 border-b py-3"><span>{x.text}{x.required?' • أساسي':''}</span><b>{x.weight}%</b></div>)}</div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظات إضافية (اختياري)" className="input mt-5 min-h-28"/></>}
 {error&&<div className="mt-5 bg-red-50 text-red-700 p-4 rounded-xl">{error}</div>}<div className="flex justify-between mt-8"><button type="button" onClick={()=>setStep(x=>Math.max(1,x-1))} disabled={step===1||saving} className="border rounded-xl px-5 py-3 font-bold flex gap-2 items-center disabled:opacity-40"><ChevronRight size={18}/> السابق</button>{step<4?<button type="button" onClick={goNext} disabled={researching} className="btn-gold rounded-xl px-6 py-3 font-bold flex gap-2 items-center disabled:opacity-50">التالي <ChevronLeft size={18}/></button>:<button type="button" onClick={submit} disabled={saving} className="btn-gold rounded-xl px-7 py-3 font-bold disabled:opacity-50">{saving?'جاري الحفظ...':'إنشاء الطلب'}</button>}</div></div></div></main>
}
