import Link from 'next/link'
import { notFound } from 'next/navigation'
import { supabase } from '@/lib/supabase'

export default async function OnboardingReport({ params }: { params: Promise<{ candidateId: string }> }) {
  const { candidateId } = await params
  const [{ data: c }, { data: o }, { data: r }] = await Promise.all([
    supabase.from('candidates').select('*').eq('id', candidateId).maybeSingle(),
    supabase.from('employee_onboarding').select('*').eq('candidate_id', candidateId).maybeSingle(),
    supabase.from('requests').select('*').eq('id', (await supabase.from('candidates').select('request_id').eq('id', candidateId).maybeSingle()).data?.request_id || '').maybeSingle(),
  ])
  if (!c || !o) notFound()
  return <main dir="rtl" className="min-h-screen bg-slate-100 p-4 print:bg-white"><style>{`@page{size:A4;margin:10mm} @media print{.no-print{display:none!important}.sheet{box-shadow:none!important;border:0!important}}`}</style><div className="sheet mx-auto max-w-[800px] bg-white border rounded-xl shadow-sm p-8 print:p-0"><div className="no-print flex justify-between mb-5"><Link href="/onboarding" className="font-bold text-[#09233f]">العودة</Link><button onClick={() => window.print()} className="btn-primary rounded-lg px-4 py-2 font-bold">طباعة</button></div><header className="text-center border-b-2 border-[#09233f] pb-5"><div className="text-[#b88618] font-bold">البنية الاساسية للمقاولات</div><h1 className="text-2xl font-black text-[#09233f] mt-2">نموذج مباشرة العمل</h1><p className="text-sm text-slate-500 mt-1">Employee Direct Work / Onboarding Form</p></header><section className="mt-6"><h2 className="font-black text-lg text-[#09233f] border-b pb-2">بيانات الموظف</h2><div className="grid grid-cols-2 gap-3 mt-4 text-sm">{[['اسم الموظف',c.full_name],['رقم الموظف',o.employee_number||'—'],['المسمى الوظيفي',o.job_title||'—'],['القسم',o.department||'—'],['المشروع / الموقع',o.project_name||'—'],['موقع العمل',o.work_location||'—'],['تاريخ المباشرة',o.direct_start_date||'—'],['حالة الموظف',o.employment_status||'—'],['نوع الحالة',o.appointment_type||'—'],['نوع العقد',o.contract_type||'—'],['المدير المباشر',o.manager_name||'—'],...(o.appointment_type==='تعيين جديد'?[['الحزمة المالية الشهرية',o.salary||'—']]:[])].map(([a,b])=><div key={a} className="border rounded-lg p-3"><div className="text-slate-500 mb-1">{a}</div><div className="font-bold">{b}</div></div>)}</div></section><section className="mt-6"><h2 className="font-black text-lg text-[#09233f] border-b pb-2">بيانات الطلب</h2><div className="grid grid-cols-2 gap-3 mt-4 text-sm"><div className="border rounded-lg p-3"><div className="text-slate-500">نوع الطلب</div><div className="font-bold mt-1">{r?.request_type||'—'}</div></div><div className="border rounded-lg p-3"><div className="text-slate-500">الوظيفة المطلوبة</div><div className="font-bold mt-1">{r?.exact_type||'—'}</div></div></div></section><section className="mt-6"><h2 className="font-black text-lg text-[#09233f] border-b pb-2">ملاحظات</h2><div className="border rounded-lg p-4 min-h-24 mt-4 text-sm whitespace-pre-wrap">{o.notes||'لا توجد ملاحظات.'}</div></section><section className="grid grid-cols-3 gap-8 mt-16 text-center text-sm"><div><div className="border-t pt-3">الموظف</div></div><div><div className="border-t pt-3">الموارد البشرية</div></div><div><div className="border-t pt-3">الإدارة</div></div></section></div></main>
}
