'use client'

import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { ArrowRight, Plus, Trash2, Save } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Req={id:string;name:string;category:string;weight:number;required:boolean;sort_order:number}
export default function EditRequest(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [request,setRequest]=useState<any>(null); const [reqs,setReqs]=useState<Req[]>([]); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{(async()=>{if(!supabase||!id)return; const [{data:r,error:re},{data:q,error:qe}]=await Promise.all([supabase.from('requests').select('*').eq('id',id).single(),supabase.from('request_requirements').select('*').eq('request_id',id).order('sort_order')]); if(re||qe){setError(re?.message||qe?.message||'تعذر تحميل الطلب');return} setRequest(r);setNotes(r?.notes||'');setReqs(q||[])})()},[id])
 const total=reqs.reduce((s,r)=>s+Number(r.weight||0),0)
 const update=(i:number,p:Partial<Req>)=>setReqs(x=>x.map((r,j)=>j===i?{...r,...p}:r)); const add=()=>setReqs(x=>[...x,{id:'new',name:'',category:'عام',weight:0,required:false,sort_order:x.length}]); const remove=(i:number)=>setReqs(x=>x.filter((_,j)=>j!==i))
 const save=async()=>{if(!supabase||!id)return; setError(''); const clean=reqs.filter(r=>r.name.trim()); if(!clean.length||Math.abs(total-100)>=.01){setError('يجب أن يكون مجموع أوزان المتطلبات 100%.');return} setSaving(true); const {error:e}=await supabase.from('requests').update({exact_type:request.exact_type,notes}).eq('id',id); if(e){setError(e.message);setSaving(false);return} const {error:de}=await supabase.from('request_requirements').delete().eq('request_id',id); if(de){setError(de.message);setSaving(false);return} const {error:ie}=await supabase.from('request_requirements').insert(clean.map((r,i)=>({request_id:id,name:r.name.trim(),category:r.category||'عام',weight:Number(r.weight)||0,required:r.required,sort_order:i}))); if(ie){setError(ie.message);setSaving(false);return} router.push(`/requests/${id}`); router.refresh() }
 if(!request)return <main className="min-h-screen grid place-items-center">جاري تحميل الطلب...</main>
 return <main className="min-h-screen bg-[#f5f7fa] p-5 md:p-10" dir="rtl"><div className="max-w-5xl mx-auto"><div className="card p-6"><div className="flex items-center justify-between gap-3"><div><div className="text-[#b88618] font-bold">تعديل طلب الموارد البشرية</div><h1 className="text-2xl font-bold text-[#09233f] mt-1">{request.exact_type}</h1></div><Link href={`/requests/${id}`} className="border rounded-xl px-4 py-2 flex items-center gap-2"><ArrowRight size={18}/> رجوع</Link></div><div className="grid md:grid-cols-2 gap-4 mt-6"><div><label className="text-sm font-bold">نوع الطلب</label><input value={request.request_type||''} disabled className="input mt-2 bg-slate-100"/></div><div><label className="text-sm font-bold">مسمى الطلب</label><input value={request.exact_type||''} onChange={e=>setRequest({...request,exact_type:e.target.value})} className="input mt-2"/></div></div><h2 className="section-title mt-8">المتطلبات والأوزان</h2><div className="space-y-3 mt-4">{reqs.map((r,i)=><div key={i} className="grid grid-cols-[1fr_110px_130px_80px_40px] gap-2 items-center"><input className="input" value={r.name} onChange={e=>update(i,{name:e.target.value})}/><input className="input" type="number" min="0" max="100" step="0.01" value={r.weight} onChange={e=>update(i,{weight:Number(e.target.value)})}/><select className="input" value={r.category} onChange={e=>update(i,{category:e.target.value})}><option>عام</option><option>مهارة فنية</option><option>برنامج هندسي</option><option>اعتماد</option><option>خبرة</option></select><label className="text-sm"><input type="checkbox" checked={r.required} onChange={e=>update(i,{required:e.target.checked})}/> أساسي</label>{reqs.length>1&&<button onClick={()=>remove(i)} className="text-red-500"><Trash2 size={18}/></button>}</div>)}</div><button onClick={add} className="mt-4 flex gap-2 items-center text-[#b88618] font-bold"><Plus size={18}/> إضافة متطلب</button><div className={`mt-4 p-4 rounded-xl font-bold ${Math.abs(total-100)<.01?'bg-green-50 text-green-700':'bg-amber-50 text-amber-700'}`}>إجمالي الأوزان: {total.toFixed(2)}%</div><textarea className="input mt-5 min-h-28" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظات"/><button disabled={saving} onClick={save} className="btn-gold mt-5 rounded-xl px-6 py-3 font-bold flex items-center gap-2">{saving?'جاري الحفظ...':<><Save size={18}/> حفظ التعديلات</>}</button>{error&&<div className="mt-4 bg-red-50 text-red-700 p-4 rounded-xl">{error}</div>}</div></div></main>
}