'use client'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {FormPage,Section,Field,Signatures} from '@/components/hrforms/FormPage'

export default function JoiningForm({params}:{params:Promise<{candidate_id:string}>}){
 const [id,setId]=useState('');const [c,setC]=useState<any>(null);const [f,setF]=useState<any>({employee_number:'',job_title:'',department:'',project_name:'',work_location:'',direct_start_date:'',employment_status:'',appointment_type:'تعيين جديد',salary:'',contract_type:'',manager_name:'',direct_work_number:'',emergency_contact_name:'',emergency_contact_phone:'',emergency_contact_relationship:'',basic_salary:'',housing_allowance:'',transportation_allowance:'',related_work:'',appointment_reason:'',notes:''});const [msg,setMsg]=useState('');const [saving,setSaving]=useState(false)
 useEffect(()=>{params.then(p=>setId(p.candidate_id))},[params]);useEffect(()=>{if(!id)return;(async()=>{const [{data:cand},{data:o}]=await Promise.all([supabase.from('candidates').select('*').eq('id',id).single(),supabase.from('employee_onboarding').select('*').eq('candidate_id',id).maybeSingle()]);setC(cand);if(o)setF((x:any)=>({...x,...o}))})()},[id])
 const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));const save=async()=>{setSaving(true);setMsg('');const payload={...f,candidate_id:id};if(f.appointment_type!=='تعيين جديد')payload.salary=null;const {error}=await supabase.from('employee_onboarding').upsert(payload,{onConflict:'candidate_id'});setSaving(false);setMsg(error?`تعذر الحفظ: ${error.message}`:'تم حفظ نموذج مباشرة العمل.')}
 return <FormPage title="مباشرة العمل" subtitle="EMPLOYEE JOINING FORM" actions={<><button onClick={save}>{saving?'جارٍ الحفظ...':'حفظ النموذج'}</button><button onClick={()=>window.print()}>طباعة / PDF</button></>}>
 {msg&&<div className="text-center text-sm mb-2">{msg}</div>}
 <Section ar="بيانات الموظف" en="EMPLOYEE INFORMATION"><Field ar="اسم الموظف" en="Employee Name" value={c?.full_name} readOnly/><Field ar="رقم الموظف" en="Employee Number" value={f.employee_number} onChange={v=>set('employee_number',v)}/><Field ar="رقم الجوال" en="Mobile" value={c?.phone} readOnly/><Field ar="المسمى الوظيفي" en="Job Title" value={f.job_title} onChange={v=>set('job_title',v)}/></Section>
 <Section ar="بيانات العمل" en="WORK INFORMATION"><Field ar="الإدارة" en="Department" value={f.department} onChange={v=>set('department',v)}/><Field ar="المشروع" en="Project" value={f.project_name} onChange={v=>set('project_name',v)}/><Field ar="موقع العمل" en="Work Location" value={f.work_location} onChange={v=>set('work_location',v)}/><Field ar="تاريخ المباشرة" en="Start Date" type="date" value={f.direct_start_date} onChange={v=>set('direct_start_date',v)}/><Field ar="الحالة الوظيفية" en="Employment Status" value={f.employment_status} onChange={v=>set('employment_status',v)}/><Field ar="نوع التعيين" en="Appointment Type" value={f.appointment_type} onChange={v=>set('appointment_type',v)}/><Field ar="نوع العقد" en="Contract Type" value={f.contract_type} onChange={v=>set('contract_type',v)}/><Field ar="المدير المباشر" en="Direct Manager" value={f.manager_name} onChange={v=>set('manager_name',v)}/></Section>
 {f.appointment_type==='تعيين جديد'&&<Section ar="الحزمة المالية الشهرية" en="MONTHLY FINANCIAL PACKAGE"><Field ar="الراتب" en="Salary" value={f.salary} onChange={v=>set('salary',v)}/><Field ar="الراتب الأساسي" en="Basic Salary" value={f.basic_salary} onChange={v=>set('basic_salary',v)}/><Field ar="بدل السكن" en="Housing Allowance" value={f.housing_allowance} onChange={v=>set('housing_allowance',v)}/><Field ar="بدل النقل" en="Transportation Allowance" value={f.transportation_allowance} onChange={v=>set('transportation_allowance',v)}/></Section>}
 <Section ar="بيانات الطوارئ والملاحظات" en="EMERGENCY & NOTES"><Field ar="اسم جهة الاتصال للطوارئ" en="Emergency Contact" value={f.emergency_contact_name} onChange={v=>set('emergency_contact_name',v)}/><Field ar="جوال الطوارئ" en="Emergency Phone" value={f.emergency_contact_phone} onChange={v=>set('emergency_contact_phone',v)}/><Field ar="صلة القرابة" en="Relationship" value={f.emergency_contact_relationship} onChange={v=>set('emergency_contact_relationship',v)}/></Section>
 <Signatures/>
 </FormPage>
}
